# Generated by Django 4.0.4 on 2022-05-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
