# Generated by Django 4.0.4 on 2022-05-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_student_message_remove_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_enrolled',
            new_name='created_at',
        ),
    ]
